import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const GRAPHHOPPER_URL = "http://localhost:8989/route";
const DEFAULT_CENTER = { lat: -22.8164, lon: -45.1927 }; // Guaratinguetá-SP center

// ---------------------------------------------------------------------------
// Map setup — OSM raster tiles (fully open, no API key)
// ---------------------------------------------------------------------------
const map = new maplibregl.Map({
  container: "map",
  style: {
    version: 8,
    sources: {
      osm: {
        type: "raster",
        tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
        tileSize: 256,
        attribution: "&copy; OpenStreetMap contributors",
      },
    },
    layers: [{ id: "osm", type: "raster", source: "osm" }],
  },
  center: [DEFAULT_CENTER.lon, DEFAULT_CENTER.lat],
  zoom: 14,
});

let startMarker = null;
let endMarker = null;

map.on("load", () => {
  map.addSource("route", {
    type: "geojson",
    data: { type: "FeatureCollection", features: [] },
  });
  map.addLayer({
    id: "route-line",
    type: "line",
    source: "route",
    layout: { "line-join": "round", "line-cap": "round" },
    paint: {
      "line-color": "#256d46",
      "line-width": 5,
      "line-opacity": 0.85,
    },
  });
});

// Click on the map to move the start point
map.on("click", (e) => {
  document.getElementById("lat").value = e.lngLat.lat.toFixed(6);
  document.getElementById("lon").value = e.lngLat.lng.toFixed(6);
  setStatus("Start point moved. Click “Generate route”.", "");
});

// ---------------------------------------------------------------------------
// UI helpers
// ---------------------------------------------------------------------------
const statusEl = document.getElementById("status");
const statsEl = document.getElementById("stats");

function setStatus(html, kind) {
  statusEl.className = kind || "";
  statusEl.innerHTML = html;
}

function fmtDuration(ms) {
  const min = Math.round(ms / 60000);
  return min >= 60 ? `${Math.floor(min / 60)} h ${min % 60} min` : `${min} min`;
}

// ---------------------------------------------------------------------------
// Route rendering
// ---------------------------------------------------------------------------
function drawRoute(ghResponse, { isSample = false } = {}) {
  const path = ghResponse.paths && ghResponse.paths[0];
  if (!path || !path.points || !path.points.coordinates) {
    throw new Error("Response has no paths[0].points.coordinates (is points_encoded=false set?)");
  }
  const coords = path.points.coordinates; // [lon, lat, (ele)]

  map.getSource("route").setData({
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "LineString", coordinates: coords.map((c) => [c[0], c[1]]) },
        properties: {},
      },
    ],
  });

  const first = coords[0];
  const last = coords[coords.length - 1];

  if (startMarker) startMarker.remove();
  if (endMarker) endMarker.remove();
  startMarker = new maplibregl.Marker({ color: "#256d46" })
    .setLngLat([first[0], first[1]])
    .setPopup(new maplibregl.Popup().setText("Start"))
    .addTo(map);
  endMarker = new maplibregl.Marker({ color: "#a3271f", scale: 0.8 })
    .setLngLat([last[0], last[1]])
    .setPopup(new maplibregl.Popup().setText("End"))
    .addTo(map);

  // Fit view to route
  const bounds = coords.reduce(
    (b, c) => b.extend([c[0], c[1]]),
    new maplibregl.LngLatBounds([first[0], first[1]], [first[0], first[1]])
  );
  map.fitBounds(bounds, { padding: 60 });

  // Loop check: distance between first and last coordinate (meters, haversine)
  const gapMeters = haversine(first[1], first[0], last[1], last[0]);
  const closes = gapMeters < 30;

  statsEl.hidden = false;
  document.getElementById("stat-distance").textContent = `${(path.distance / 1000).toFixed(2)} km`;
  document.getElementById("stat-duration").textContent = fmtDuration(path.time);
  document.getElementById("stat-loop").textContent = closes
    ? `yes (gap ${gapMeters.toFixed(1)} m)`
    : `NO — gap ${gapMeters.toFixed(1)} m`;

  const sampleBadge = isSample
    ? ' <span class="sample-badge">SAMPLE DATA — not live routing</span>'
    : "";
  setStatus(
    (isSample ? "Rendered bundled sample response." : "Route generated by local GraphHopper.") +
      sampleBadge,
    isSample ? "warn" : "ok"
  );
}

function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371000;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

// ---------------------------------------------------------------------------
// GraphHopper request
// ---------------------------------------------------------------------------
async function generateRoute(lat, lon, distanceKm, seed) {
  const params = new URLSearchParams({
    point: `${lat},${lon}`,
    profile: "foot",
    algorithm: "round_trip",
    "round_trip.distance": String(Math.round(distanceKm * 1000)),
    "round_trip.seed": String(seed),
    points_encoded: "false",
    "ch.disable": "true",
  });

  const res = await fetch(`${GRAPHHOPPER_URL}?${params}`);
  const body = await res.json().catch(() => null);
  if (!res.ok) {
    const msg = body && body.message ? body.message : `HTTP ${res.status}`;
    throw new Error(msg);
  }
  return body;
}

// ---------------------------------------------------------------------------
// Form wiring
// ---------------------------------------------------------------------------
document.querySelectorAll(".preset").forEach((btn) => {
  btn.addEventListener("click", () => {
    document.getElementById("distance").value = btn.dataset.km;
  });
});

document.getElementById("route-form").addEventListener("submit", async (e) => {
  e.preventDefault();
  const lat = parseFloat(document.getElementById("lat").value);
  const lon = parseFloat(document.getElementById("lon").value);
  const km = parseFloat(document.getElementById("distance").value);
  const seed = parseInt(document.getElementById("seed").value || "0", 10);

  const btn = document.getElementById("generate");
  btn.disabled = true;
  setStatus("Generating route…", "");

  try {
    const response = await generateRoute(lat, lon, km, seed);
    drawRoute(response);
  } catch (err) {
    // GraphHopper unreachable → fall back to the bundled SAMPLE response so the
    // map still demonstrates rendering. Clearly labeled; never pretends to be live.
    if (err instanceof TypeError) {
      try {
        const sample = await fetch("/sample-route.json").then((r) => r.json());
        drawRoute(sample, { isSample: true });
        setStatus(
          'Could not reach GraphHopper at <code>localhost:8989</code>. ' +
            'Showing bundled <span class="sample-badge">SAMPLE</span> instead. ' +
            "Start the backend (see README) for live routing.",
          "warn"
        );
      } catch {
        setStatus("GraphHopper unreachable and sample missing: " + err.message, "error");
      }
    } else {
      setStatus("Routing error: " + err.message, "error");
    }
  } finally {
    btn.disabled = false;
  }
});
